version: '3.8'

services:
    db:
        image: mysql:5.7
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpass
            MYSQL_DATABASE: course_laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: 12345

    web:
        tty: true
        stdin_open: true
        build:
            context: "."
            dockerfile: ./docker/web/Dockerfile
        command: /scripts/entrypoint.sh
        # environment:
        #     PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin
        volumes:
            - .:/var/www/html
            - ./docker/web/scripts:/scripts
        depends_on:
            - db
        ports:
            - "8000:8000"

    mailhog:
        image: mailhog/mailhog
        logging:
            driver: 'none'  # disable saving logs
        ports:
        - "8025:8025"
volumes:
  mysql:
