version: '3.8'

services:
    db:
        image: mysql:5.7
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpass
            MYSQL_DATABASE: course_laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: 12345

    web:
        tty: true
        stdin_open: true
        build:
            context: "."
            dockerfile: ./docker/web/Dockerfile
        command: /scripts/entrypoint.sh
        volumes:
            - .:/var/www/html
            - ./docker/web/scripts:/scripts
        depends_on:
            - db
        ports:
            - "9000"

    nginx:
        tty: true
        stdin_open: true
        image: nginx:alpine
        volumes:
            - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
            - ./public/:/var/www/html/public/
        depends_on:
            - web
        ports:
            - "80:80"

    mailhog:
        image: mailhog/mailhog
        logging:
            driver: 'none'  # disable saving logs
        ports:
        - "8025:8025"
volumes:
  mysql:
