version: '3.8'

services:
    db:
        image: mysql:5.7
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpass
            MYSQL_DATABASE: course_laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        links:
            - db
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: 12345

    web:
        tty: true
        stdin_open: true
        command: sh /docker-entrypoint.sh
        build: ./docker-dev/web
        links:
            - db
        ports:
            - "8000:8000"
        environment:
            APP_DEBUG: 'true'
            XDEBUG_MODE: coverage
            PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin
        volumes:
            - .:/app:cached
            - ./docker-dev/web/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

    mailhog:
        image: mailhog/mailhog
        logging:
            driver: 'none'  # disable saving logs
        ports:
        - "8025:8025"
volumes:
  composer_caches:
  mysql:
